steps:
  - task: DownloadSecureFile@1
    name: workbooksProperties
    displayName: 'Download workbooks space details'
    inputs:
      secureFile: 'workbooks.properties'

  - bash: |
      cp $(workbooksProperties.secureFilePath) $(System.DefaultWorkingDirectory)/repos/$(workbooks_file)
    displayName: Overwrite workbooks.properties file