trigger:
- base

pool:
  vmImage: 'Ubuntu-16.04'



variables:
  imageName: 'appxx-img'
  dockerfilePath: 'bulletin-board-app/Dockerfile'
  dockerRegistryServiceConnection: boostRegistryServiceConnection
  armServiceConnectionBoost: boostAzureServiceConnection
  appName: appxx
  container: appxx.azurecr.io/appxx-img:latest

stages:
- stage: Build
  displayName: Test, Build and Push docker image
  jobs:
  - job: Build
    displayName: Build job
    steps:
    - bash: |
        echo "I would run unit,integration tests here"
      displayName: Unit and Integration Tests

    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageName)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          latest

- stage: Deploy
  displayName: Deploy App
  jobs:
  - job:
    steps:
    - task: AzureWebAppContainer@1 # Add this at the end of your file
      displayName: Deploy
      inputs:
        azureSubscription: '$(armServiceConnectionBoost)'
        appName: '$(appname)'
        containers: $(container)

- stage: E2E_Tests_Sel
  displayName: E2E Tests Selenium
  jobs:
    - job: Selenium
      displayName: Selenium job
      steps:
        - bash: |
            echo "I would run Selenium tests here"
          displayName: Selenium Tests

