trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'appxx-img'
  dockerfilePath: 'bulletin-board-app/Dockerfile'
  dockerRegistryServiceConnection: boostRegistryServiceConnection
  armServiceConnection: boostAzureServiceConnection
  appName: appxx
  container: appxx.azurecr.io/appxx-img:latest

stages:
- stage: Build
  displayName: Build and Push docker image
  jobs:  
  - job: Build
    displayName: Build job
    steps:
    - bash: |
        echo "I would run unit,integration tests here"
      displayName: Tests
      
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageName)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          latest

- stage: Deploy
  displayName: Deploy App
  jobs:
  - job:
    steps:
    - task: AzureWebAppContainer@1 # Add this at the end of your file
      displayName: Deploy
      inputs:
        azureSubscription: '$(armServiceConnection)'
        appName: '$(appname)'
        containers: $(container)
   
- stage: E2E_Tests
  displayName: E2E Tests
  jobs:
  - job:
    steps:
    - bash: |
        echo "I would run Selenium here"
      displayName: Selenium Tests
