trigger:
- base

pool:
  vmImage: 'Ubuntu-16.04'


resources:
  repositories:
    - repository: crux
      type: github
      name: ObjectivityLtd/crux
      ref: refs/heads/release/0.5.0
      endpoint: crux

    - repository: tests
      type: github
      name: gabrielstar/node-bulletin-board
      ref: refs/heads/base
      endpoint: crux


parameters:
  - name: mode
    default: jmeter
    values:
      - jmeter
      - jmeter_with_dynamic_pools
      - jmeter_dynamic
      - tests
  - name: jmeter_slaves
    default: 1
    type: number

  - name: jmx
    default: .crux/test/script/bulletin.jmx
    type: string

  - name: jmeter_args
    default: "-Gthreads=1 -Gloops=1 -Gwait=1 -Gdata_dir=/shared"
    type: string

  - name: kubernetes_service_connection
    default: k8
    type: string

  - name: arm_service_connection
    default: _
    type: string

variables:
  imageName: 'appxx-img'
  dockerfilePath: 'bulletin-board-app/Dockerfile'
  dockerRegistryServiceConnection: boostRegistryServiceConnection
  armServiceConnectionBoost: boostAzureServiceConnection
  appName: appxx
  container: appxx.azurecr.io/appxx-img:latest

  #user-defined - configure during set-up
  repoName: node-bulletin-board
  cluster_name: k8
  clusterNodeSize: Standard_D2_v2
  clusterNodeNumber: 2
  rgroup: az900
  namespace: default

  #adjust paths to repo structure
  crux_file: $(repoName)/.crux/test/config/crux.properties
  thresholds_file: $(repoName)/.crux/test/config/thresholds.properties
  workbooks_file: $(repoName)/.crux/test/config/workbooks.properties
  data_dir_relative: .crux/test/test_data

  #read-only - do not change unless you know what you are doing
  cruxRepoName: crux
  cluster_namespace: crux$(Build.BuildID)
  kubernetesServiceConnection: ${{ parameters.kubernetes_service_connection }}
  scale_up_replicas: ${{ parameters.jmeter_slaves }}
  jmeter_args: ${{ parameters.jmeter_args }}
  scenario: $(repoName)/${{ parameters.jmx }}
  armServiceConnection: ${{ parameters.arm_service_connection }}
  data_dir: $(repoName)/$(data_dir_relative)

stages:
- stage: Build
  displayName: Test, Build and Push docker image
  jobs:
  - job: Build
    displayName: Build job
    steps:
    - bash: |
        echo "I would run unit,integration tests here"
      displayName: Unit and Integration Tests

    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageName)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          latest

- stage: Deploy
  displayName: Deploy App
  jobs:
  - job:
    steps:
    - task: AzureWebAppContainer@1 # Add this at the end of your file
      displayName: Deploy
      inputs:
        azureSubscription: '$(armServiceConnectionBoost)'
        appName: '$(appname)'
        containers: $(container)

- stage: E2E_Tests_Sel
  displayName: E2E Tests Selenium
  jobs:
    - job: Selenium
      displayName: Selenium job
      steps:
        - bash: |
            echo "I would run Selenium tests here"
          displayName: Selenium Tests

- stage: E2E_Tests
  displayName: E2E Tests Performance
  jobs:
    - template: .crux/.template/crux.template.yaml
      parameters:
        mode: ${{ parameters.mode }}
        arm_service_connection: ${{ parameters.arm_service_connection }}
        kubernetes_service_connection: ${{ parameters.kubernetes_service_connection }}