# This pipeline requires azure service connection of type "kubernetes service"
# Remember to have 1-1 jmeter service to k8 node (VM)/pod ratio - otherwsie some slaves can crash due to lack of resources

name: $(BuildID)
trigger: none
#config
parameters:
  - name: mode
    displayName: 'Which template to use ?'
    type: string
    default: deploy
    values:
      - deploy
      - delete

  - name: kubernetesServiceConnection
    displayName: 'Connection ?'
    type: string
    default: k8

  - name: namespace
    displayName: 'Namespace ?'
    type: string
    default: default

variables:
  namespace: default #edit

jobs:
  - job: JMeter_Tests
    displayName: Attach to existing cluster
    pool:
      vmImage: 'ubuntu-latest'
    timeoutInMinutes: 5
    steps:

    - task: Kubernetes@1
      displayName: Login to cluster
      inputs:
        command: login
        connectionType: Kubernetes Service Connection
        kubernetesServiceEndpoint: ${{ parameters.kubernetesServiceConnection }}

    - bash: |
        kubectl delete -n $(namespace) deployment/jmeter-slaves deployment/jmeter-master svc/jmeter-slaves-svc configmap/jmeter-load-test pvc/jmeter-shared-disk  ||:
        kubectl delete sc/jmeter-shared-disk-sc ||: #this is not cluster-scoped resource hence dropping the namespace
      displayName: Delete existing deployment

    - bash: |
        kubectl create  -n $(namespace) -f kubernetes/config/deployments/jmeter_shared_volume_sc.yaml
        kubectl create  -n $(namespace) -f kubernetes/config/deployments/jmeter_shared_volume.yaml
        kubectl create  -n $(namespace) -f kubernetes/config/deployments/jmeter_slaves_deploy_v16.yaml
        kubectl create  -n $(namespace) -f kubernetes/config/deployments/jmeter_slaves_svc.yaml
        kubectl create  -n $(namespace) -f kubernetes/config/deployments/jmeter_master_configmap.yaml
        kubectl create  -n $(namespace) -f kubernetes/config/deployments/jmeter_master_deploy_v16.yaml
      condition: and(succeeded(), not(eq('${{ parameters.mode }}', 'delete')))
      displayName: Deploy services to cluster
